### PR TITLE
Desktop application in python

### PR DESCRIPTION
**Pull request by starrohan999**
create a desktop application with the help of python and Tkinter module. it helps the kid to learn the basics of python. which is far better than pdf learning.it have all content for kids to learn the basics of python
#python development

### CODE REVIEW

**Comment by starrohan999** [comment]
hey @harshitbansal373. please review it and merged it.
hii HARSHIT BANSAL  SIR , this  is a kind of mini-project  that I made during the lockdown please review it and merged it .
please

**Comment by starrohan999** [comment]
OUTPUT

**Comment by starrohan999** [comment]
please review it sir and merged it 
please.

**Review by harshitbansal373 — APPROVED** [review]
Good start!
keep going!!!

**Pull request merged**
