### PR TITLE
created Directories and removed/fixed Non Working Algos

### PR DESCRIPTION
**Pull request by prkhrv**

### CODE REVIEW

**Comment by harshitbansal373** [comment]
Resolve conflict

**Comment by prkhrv** [comment]
@harshitbansal373 Hi, I do appreciate You letting everyone to contribute but please do check programs/algorithms before merging them many of them were without any extension.
and Please ask the contributors to add files to the respected Directories.

**Comment by prkhrv** [comment]
@harshitbansal373  You Should be merging this before adding any, Your repo is Not Useful everything is just haywire.

**Comment by harshitbansal373** [comment]
I already told some of folks but I have not so much time to have discussion with everyone so folks like you can arrange this so in future everyone contribute in manner. Although this all are not just haywire, it's collection of codes, folks like you can also arrange this in effective manner, you're welcome....and take care about conflicts...push it after resolve

**Pull request closed without merging**
