### PR TITLE
Print Prime numbers from 2 to the number using SOE [Optimized Algorit…

### PR DESCRIPTION
**Pull request by akshatagrawal9874**
…hm] .i.e Time Complexity :O(log n)

Print Prime numbers from 2 to the number using SOE [Optimized Algorithm].i.e Time Complexity :O(log n)

### CODE REVIEW

**Comment by akshatagrawal9874** [comment]
If you want to merge, please labeled as "hacktoberfest-accepted"

**Comment by MANISH007700** [comment]
Can i work on this ? @akshatagrawal9874

**Comment by MANISH007700** [comment]
This is the drive link of the code to print prime num till the nth number !
Please label it as 'Hacktoberfest' Accepted to get those sweet sweet Tees :)

[Python_code_for_prime_num(https://drive.google.com/file/d/15MMaga_w6RkdyWM4_j7qHgD10OnhzEEx/view?usp=drivesdk)

**Review by harshitbansal373 — APPROVED** [review]

**Comment by akshatagrawal9874** [comment]
Please labeled as "hacktoberfest-accepted"

**Comment by MANISH007700** [comment]
Please add hacktoberfest accepted

**Pull request merged**
