### PR TITLE
add Wilson's Theorem for check if number is prime

### PR DESCRIPTION
**Pull request by mko010**

### CODE REVIEW

**Review by harshitbansal373 — COMMENTED** [review]
it's not the proper way

**Comment by mko010** [comment]
> it's not the proper way

Why this is not the proper way, for the last line?

**Comment by harshitbansal373** [comment]
mentioned full program with proper syntax

**Comment by mko010** [comment]
> mentioned full program with proper syntax

Do you refer an explanation of theorem and an example?

**Comment by harshitbansal373** [comment]
yeah! sort of... It might help to understand.

**Comment by mko010** [comment]
> yeah! sort of... It might help to understand.

Oh, sorry for the misunderstanding. Later I fix it.

**Comment by harshitbansal373** [comment]
No issue!

**Review by harshitbansal373 — APPROVED** [review]

**Pull request merged**
