### PR TITLE
htmlFile added

### PR DESCRIPTION
**Pull request by ojaswi143**

### CODE REVIEW

**Review by harshitbansal373 — COMMENTED** [review]
Please, put the file under HTML files folder (if folder doesn't exist then make it) and rename your HTML file with the proper name.

**Comment by ojaswi143** [comment]
Ohk thank you ,I will do it now

**Review by harshitbansal373 — APPROVED** [review]
Now it's better!

**Comment by ojaswi143** [comment]
THANKS A LOT

**Pull request merged**
